---
apiVersion: v1
kind: Secret
metadata:
  name: mjaekel73-poi-map-app-repo
  namespace: janus-argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  url: https://github.com/rhdh23-lab/mjaekel73-frontend-gitops
